---
- name: Webserver - Deployment
  hosts: all
  tasks:
    
    - name: Install httpd package
      dnf:
        name: httpd
        state: latest
    
    - name: Start and enable httpd service
      service:
        name: httpd
        enabled: true
        state: started

    - name: Create a custom index.html file
      copy:
        dest: /var/www/html/index.html
        content: |
          this is Ragesh's test page
EOF

