name: Automation Tests

on:
  push:
    branches: 
      - task/INTOOLS-1290_ui_automation_tests

jobs:
  my_job:
    runs-on : ubuntu-latest
  container:
    runs-on: ubuntu-latest
    container: selenium/standalone-chrome:latest
      ports:
        - 4444:4444
      volumes:
        - /home/runner/work/xenomorph/xenomorph:/test
      options: --shm-size="2g"
       
    steps:
      - name : Checkout
        uses : actions/checkout@v2
        
      - name : Setup
        run: |
          curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
          sudo apt install nodejs
          sudo apt install make
      - name: Run Automation Test Suite
        run: |
          make clean install build
          npm i chromedriver
          cd packages/xenomorph-drone/
          npm run automation
